name: yoyo_player
description: yoyo_player is a video player that allows you to select HLS video
  streaming by selecting the quality
version: 0.1.0
homepage: https://github.com/ko-htut/yoyo-player.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  orientation: ^1.3.0
  path_provider: ^2.0.2
  flutter_screen_wake: ^1.0.2
  video_player: ^2.2.18
  video_player_web_hls: ^0.1.11+4
  wakelock: ^0.5.2
  syncfusion_flutter_sliders: ^19.2.51
  syncfusion_flutter_core: ^19.2.51

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: 

  uses-material-design: true
# To add assets to your package, add an assets section, like this:
  assets:
    - images/icon_full_screen.png
    - images/icon_sound.png
    - images/icon_exit_full.png
  # - img/icon_sound.png
  # - img/icon_full_screen.png 
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
